# Generated by Django 4.2.3 on 2023-07-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_money_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaydate',
            name='daysInGame',
            field=models.IntegerField(default=0),
        ),
    ]
