# Generated by Django 4.2.3 on 2023-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_todaydate_daysingame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2010-01-04')),
                ('portfolioValue', models.FloatField(null=True)),
            ],
        ),
    ]
